# Module1 BUCK file
java_library(
    name = "crypto_utils",
    srcs = glob(["*.java"]),
    deps = [
        ":conscrypt",
    ],
    visibility = ["PUBLIC"],
)

prebuilt_jar(
    name = "conscrypt",
    binary_jar = "libs/conscrypt-android-2.5.2.jar",
)