workspace(name = "crypto_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# BouncyCastle dependency
maven_jar(
    name = "bouncycastle_bcprov",
    artifact = "org.bouncycastle:bcprov-jdk15on:1.70",
)

maven_jar(
    name = "bouncycastle_bcpkix",
    artifact = "org.bouncycastle:bcpkix-jdk15on:1.70",
)

# Google Tink for crypto
maven_jar(
    name = "tink",
    artifact = "com.google.crypto.tink:tink:1.7.0",
)