# Submodule BUCK file  
java_library(
    name = "advanced_crypto",
    srcs = glob(["*.java"]),
    deps = [
        ":tink",
        ":bouncycastle_pkix",
    ],
    visibility = ["PUBLIC"],
)

prebuilt_jar(
    name = "tink",
    binary_jar = "libs/tink-1.7.0.jar",
)

prebuilt_jar(
    name = "bouncycastle_pkix",
    binary_jar = "libs/bcpkix-jdk15on-1.70.jar",
)