[package]
name = "detector-objc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
scanner-core = { path = "../scanner-core" }
anyhow = { workspace = true }

[lib]
name = "detector_objc"
path = "src/lib.rs"
