# Root BUCK file
java_library(
    name = "root_crypto",
    srcs = glob(["root/*.java"]),
    deps = [
        ":bouncycastle_core",
        "//module1:crypto_utils",
        "//module2/submodule:advanced_crypto",
    ],
    visibility = ["PUBLIC"],
)

prebuilt_jar(
    name = "bouncycastle_core",
    binary_jar = "libs/bcprov-jdk15on-1.70.jar",
)